### ISSUE TITLE
Hunts Utilities Attacking Incorrect Mobs

### ISSUE THREAD

**Issue by Warcren** [nt153133/LlamaUtilities#4]
Greetings,

I am unsure if this has been mentioned before or if it has been droped but the Hunt Utility is not working correctly. It's targeting and killing mobs that are not part of the Hunt target and it remains indefinitly hunting said targets.

I tried it with all 4 Hunt settings.

ARR -> Stuck on Bloodshore Bells
HW -> Stuck on Lone Yetis
StormBlood ->  Goosefish
SB -> Gnole

**Comment by nt153133** [comment]
When was the last time you updated LL https://github.com/nt153133/__LlamaLibrary? I pushed the fix to that on 1/2 which is about the same time as you opened the issue so it could have just been poor timing
